name: GamblePlugin
main: me.gambleplugin.GamblePlugin
version: 1.0
api-version: 1.16
commands:
  balance:
    description: Check your coin balance
  casino:
    description: Play a gamble game
  buycoins:
    description: Link to buy coins
  addcoins:
    description: Admin add coins
    usage: /addcoins <player> <amount>
